### ISSUE TITLE
unofficial "tune" command : how does it work ?

### ISSUE THREAD

**Issue by tissatussa** [cimarronOST/Monolith#15]
In your README, under "Additional unofficial commands", you describe a 'tune' option :

`tune [positions.epd] [threads]: Tuning the evaluation parameters with a set of positions. This option is only available if the compilation target tune was chosen.`

To try this, i first compiled such binary (on Linux) by doing :

`make ARCH=x64-pext tune`

and indeed the resulting binary file differs; its size is 330 Kb compared to 297 Kb for the normal executable file. Also now the 'tune' command gives output (although it seems useless when no EPD file is given as parameter).

I did not yet try to 'tune' Monolith by any EPD file, because i don't fully understand this process and i can not imagine a way to test the result. First question that comes to mind : when processing such tune command, will Monolith create a 'tuned file' or any config file which holds the result ?  Or will the binary itself be changed ? -i guess not .. How does 'tune' work ?  Can you point us to information of such process or give an example ?

**Comment by cimarronOST** [comment]
Monolith will not change the binary while tuning, it will also not create a special tuning file.
What I usually do when I do a tuning session: In the beginning I set the 'Log' option to 'true' in order to redirect all engine output to a log-file. Then I start the tuning with the 'tune file.epd' command. During the tuning process, at every iteration Monolith will output the current best values, until no better values can be found and the tuning is complete. I than insert the new evaluation values by hand into the source files, recompile them and test the engine by running a lot of bullet games. If everything went well, the new values will result in an Elo gain, but the process is a lot of trial and error and depends heavily on the set of EPD-positions.

The original Texel Tuning Method is used without much optimization in Monolith, other engines have adopted more sophisticated algorithms. The new NNUE engines don't even need such tuning of the hand crafted evaluation function anymore. NNUE provides a much better evaluation than a hand crafted evaluation ever could, no matter how good it is tuned.
You can find out more about the Texel Tuning Method and how it works [at the chess programming wiki](https://www.chessprogramming.org/Texel's_Tuning_Methodl).

**Comment by tissatussa** [comment]
> ..the process [..] depends heavily on the set of EPD-positions..

i understand and can imagine that .. but this way, can we conclude ANY set of EPDs will result in a sub-optimal tuning ?  So, this is not the way to go ?  I'm a passionated chess player myself and i know many type of positions exist ..
